### ISSUE TITLE
get_room_id results in 400 error

### ISSUE THREAD

**Issue by makeworld-the-better-one** [Pipoline/rocket-python#52]
```
>>> api.get_room_id("livestream")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/makeworld/.local/lib/python3.8/site-packages/rocketchat/api.py", line 122, in get_room_id
    return GetRoomId(settings=self.settings, **kwargs).call(
  File "/home/makeworld/.local/lib/python3.8/site-packages/rocketchat/calls/base.py", line 117, in call
    result.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://<rocketchatdomain>/api/v1/groups.info?roomName=livestream
```
This was a logged in API, and other API calls that require login like `send_message` worked fine. Maybe login info isn't being sent for this call by mistake?

**Comment by pipozzz** [comment]
Let me ensure you are calling this right.
This call desc from API doc is :
**Retrieves the information about the private group, only if you're part of the group.**
